'use client';

import { useState, useRef, useEffect, memo } from 'react';
import { TimelineItem } from '../../../stores/proposal-store';
import { Button } from '../../ui/button';
import { Input } from '../../ui/input';
import { Calendar as CalendarIcon } from 'lucide-react';
import { useProposalStore } from '../../../stores/proposal-store';
import { cn } from '../../../lib/utils/cn';
import { Textarea } from '../../ui/textarea';
import { motion, AnimatePresence } from 'framer-motion';

interface TimelineEditorProps {
  items?: TimelineItem[];
  onChange?: (items: TimelineItem[]) => void;
  readOnly?: boolean;
  isLive?: boolean;
  isAdjustmentMode?: boolean;
}

export const TimelineEditor = memo(function TimelineEditor({
  items,
  onChange,
  readOnly = false,
  isLive = false,
  isAdjustmentMode = false
}: TimelineEditorProps) {
  const store = useProposalStore();
  const executionTimeline = items || store.executionTimeline;
  const updateField = onChange ? (val: any) => onChange(val) : (val: any) => store.updateField('executionTimeline', val);

  const [editingId, setEditingId] = useState<string | null>(null);
  const containerRef = useRef<HTMLDivElement>(null);

  const isLocked = readOnly || (isLive && !isAdjustmentMode);

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (containerRef.current && !containerRef.current.contains(event.target as Node)) {
        setEditingId(null);
      }
    };
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  const handleUpdate = (id: string, field: keyof TimelineItem, value: any) => {
    if (isLocked) return;
    const updatedTimeline = executionTimeline.map(item =>
      item.id === id ? { ...item, [field]: value } : item
    );
    updateField(updatedTimeline);
  };

  const fieldContainerClass = cn(
    "py-4 border-b border-border/40 last:border-0 grid grid-cols-1 md:grid-cols-12 gap-4 items-start relative",
    isLocked && "border-border/60"
  );

  const inputStyle = cn(
    "h-11 text-sm font-medium rounded-3xl transition-all duration-200 w-full",
    isLocked
      ? "bg-transparent border-transparent shadow-none font-bold text-foreground cursor-default focus-visible:ring-0 px-1"
      : "bg-muted/20 border-border/50 focus:bg-background focus:border-primary/50 px-4"
  );

  return (
    <div className="space-y-4" ref={containerRef}>
      <div className="space-y-1">
        <AnimatePresence initial={false} mode="popLayout">
          {executionTimeline.length === 0 ? (
            <div className="py-6 text-center text-xs text-muted-foreground italic font-medium border border-dashed rounded-3xl border-border/60 bg-muted/5">
              Phases will automatically generate here based on the funding stages selected in the Use of Funds section.
            </div>
          ) : executionTimeline.map((item, index) => {
            const isEditing = editingId === item.id;

            return (
              <motion.div
                key={item.id}
                layout
                initial={{ opacity: 0, height: 0 }}
                animate={{ opacity: 1, height: 'auto' }}
                exit={{ opacity: 0, height: 0, overflow: 'hidden' }}
                transition={{ duration: 0.2 }}
                className={fieldContainerClass}
              >
                {/* PHASE TITLE (READ-ONLY AUTOGENERATED) */}
                <div className="md:col-span-3 space-y-1.5">
                  <label className="text-xs font-bold text-muted-foreground ml-1">Phase</label>
                  <div className="flex items-center gap-2">
                    <div className="h-6 w-6 rounded-full bg-primary/10 text-primary flex items-center justify-center text-[10px] font-black shrink-0 border border-primary/20">
                      {index + 1}
                    </div>
                    <Input value={item.phase || 'Main Stage'} readOnly className={cn(inputStyle, "bg-transparent border-transparent px-1 font-bold text-foreground shadow-none cursor-default focus-visible:ring-0")} />
                  </div>
                </div>

                {/* ESTIMATED DATE */}
                <div className="md:col-span-3 space-y-1.5">
                  <label className="text-xs font-bold text-muted-foreground ml-1">Due date (Optional)</label>
                  <div className="relative">
                    {!isLocked && <CalendarIcon className="absolute right-4 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground pointer-events-none" />}
                    <Input
                      type={isLocked ? "text" : "date"}
                      value={item.estimatedDate}
                      onChange={(e) => handleUpdate(item.id, 'estimatedDate', e.target.value)}
                      readOnly={isLocked}
                      className={cn(inputStyle, "tabular-nums", isLocked && "text-primary font-bold")}
                    />
                  </div>
                </div>

                {/* DELIVERABLES */}
                <div className="md:col-span-6 flex gap-2 items-end relative">
                  <div className="flex-1 space-y-1.5 min-w-0">
                    <label className="text-xs font-bold text-muted-foreground ml-1">Required Deliverables</label>
                    <div className="relative">
                      <Input
                        placeholder="Expected outcomes or proof of work..."
                        className={cn(inputStyle, isLocked && "italic font-medium text-muted-foreground")}
                        value={item.deliverables}
                        readOnly={true}
                        onClick={() => !isLocked && setEditingId(item.id)}
                      />
                      {!isLocked && isEditing && (
                        <div className="absolute top-0 left-0 w-full z-20 animate-in zoom-in-95 duration-150 origin-top-left">
                          <div className="bg-card border border-border/60 rounded-3xl shadow-2xl p-1">
                            <Textarea
                              value={item.deliverables}
                              onChange={(e) => handleUpdate(item.id, 'deliverables', e.target.value)}
                              className="min-h-[100px] w-full border-none focus-visible:ring-0 text-sm p-4 bg-transparent rounded-3xl"
                              placeholder="Detail the expected outcomes that vendors must provide..."
                            />
                            <div className="flex justify-end p-2 border-t border-border/40 bg-muted/10 rounded-b-[24px]">
                              <Button size="sm" className="h-9 text-xs font-bold rounded-2xl px-6" onClick={() => setEditingId(null)}>Done</Button>
                            </div>
                          </div>
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              </motion.div>
            );
          })}
        </AnimatePresence>
      </div>
    </div>
  );
});